// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

using Microsoft.VisualStudio.GraphModel;
using Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.GraphNodes.ViewProviders;
using Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Snapshot;

namespace Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.GraphNodes.Actions
{
    /// <summary>
    ///     Base class for graph action handlers that operate on a set of input nodes,
    ///     each of which is backed by an <see cref="IDependency"/>.
    /// </summary>
    internal abstract class InputNodeGraphActionHandlerBase : GraphActionHandlerBase
    {
        private readonly IProjectIdentityService _projectIdentityService;

        protected InputNodeGraphActionHandlerBase(
            IAggregateDependenciesSnapshotProvider aggregateSnapshotProvider,
            IProjectIdentityService projectIdentityService)
            : base(aggregateSnapshotProvider)
        {
            _projectIdentityService = projectIdentityService;
        }

        protected abstract bool CanHandle(IGraphContext graphContext);

        protected abstract void ProcessInputNode(
            IGraphContext graphContext,
            GraphNode inputGraphNode,
            IDependency dependency,
            IDependenciesSnapshot snapshot,
            IDependenciesGraphViewProvider viewProvider,
            IProjectIdentity projectId,
            ref bool trackChanges);

        public sealed override bool TryHandleRequest(IGraphContext graphContext)
        {
            if (!CanHandle(graphContext))
            {
                return false;
            }

            bool trackChanges = false;

            foreach (GraphNode inputGraphNode in graphContext.InputNodes)
            {
                if (graphContext.CancelToken.IsCancellationRequested)
                {
                    return trackChanges;
                }

//                string projectPath = inputGraphNode.Id.GetValue(CodeGraphNodeIdName.Assembly);
                IProjectIdentity projectId = inputGraphNode.Id.GetProjectId();

                if (projectId == null)
                {
                    // This is a top-level graph node, created implicitly from a tree item
                    string projectPath = inputGraphNode.Id.GetAssemblyPath();

                    // We must look up its project ID by its path
                    if (!_projectIdentityService.TryGetProjectId(projectPath, out projectId))
                    {
                        continue;
                    }
                }

//                IDependency dependency = FindDependency(projectId, inputGraphNode, out IDependenciesSnapshot snapshot);

//            IProjectIdentity projectId = inputGraphNode.Id.GetProjectId();
////            string projectPath = inputGraphNode.Id.GetValue(CodeGraphNodeIdName.Assembly);
//
//            if (projectId == null)
//            {
//                snapshot = null;
//                return null;
//            }
//
//            string projectFolder = Path.GetDirectoryName(projectPath);
//
//            if (projectFolder == null)
//            {
//                snapshot = null;
//                return null;
//            }

                string id = inputGraphNode.GetValue<string>(DependenciesGraphSchema.DependencyIdProperty);

                bool topLevel;

                if (id == null)
                {
                    // this is top level node and it contains full path 
                    id = inputGraphNode.Id.GetDependencyModelId();

                    if (id == null)
                    {
                        // No full path, so this must be a node generated by a different provider.
                        continue;
                    }

//                if (id.StartsWith(projectFolder, StringComparisons.Paths))
//                {
//                    int startIndex = projectFolder.Length;
//
//                    // Trim backslashes (without allocating)
//                    while (startIndex < id.Length && id[startIndex] == '\\')
//                    {
//                        startIndex++;
//                    }
//
//                    id = id.Substring(startIndex);
//                }

                    topLevel = true;
                }
                else
                {
                    topLevel = false;
                }

                IDependenciesSnapshot snapshot = AggregateSnapshotProvider.GetSnapshot(projectId);

                IDependency dependency = snapshot?.FindDependency(id, topLevel);

                if (dependency == null)
                {
                    continue;
                }

                IDependenciesGraphViewProvider viewProvider = FindViewProvider(dependency);

                if (viewProvider == null)
                {
                    continue;
                }

                using (var scope = new GraphTransactionScope())
                {
                    ProcessInputNode(graphContext, inputGraphNode, dependency, snapshot, viewProvider, projectId, ref trackChanges);

                    scope.Complete();
                }
            }

            return trackChanges;
        }
    }
}
